version: "3.3"
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: tiny_url
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"

    ports:
      - 6033:3306
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root--execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10

  tiny-url-create:
    restart: on-failure
    build: ./tiny-url-create-service
    expose:
      - "8081"
    ports:
      - 8081:8081
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql

  tiny-url-handle:
    restart: on-failure
    build: ./tiny-url-handle-service
    expose:
      - "8082"
    ports:
      - 8082:8082
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql

  tiny-url-statistics:
    restart: on-failure
    build: ./tiny-url-statistics-service
    expose:
      - "8083"
    ports:
      - 8083:8083
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
